---
- name: Install node.js, direnv, mongodb, redis, java, android-sdk and ionic
  hosts: all
  sudo: yes
  roles:
    - martinmicunda.common
    - martinmicunda.nodejs
    - martinmicunda.ionic
    - laggyluke.direnv
    - Stouts.mongodb
    - DavidWittman.redis
    - williamyeh.oracle-java
    - nickp666.android-sdk
  vars:
    java_version: 7
    android_sdk_download_location: http://dl.google.com/android/android-sdk_r24.1.2-linux.tgz
    android_sdk_install_location: /home/vagrant/android-sdk-linux
    android_sdk_dependency_packages:
      - "libncurses5" #libncurses5:i386
#      - "libstdc++6" #libstdc++6:i386
      - "lib32stdc++6"
      - "zlib1g" #zlib1g:i386
      - "lib32z1"
      - "imagemagick"
      - "expect"
      - "ant"
      - "ccache"
      - "autoconf"
      - "automake"
      - "python-dev"
      - "zlibc"
      - "android-tools-adb"
    android_sdks_to_install: "platform-tool,build-tools-22.0.1,build-tools-21.1.2,build-tools-20.0.0,build-tools-19.1.0,android-22,android-21,android-20,android-19"

